window.onload = function () {
    console.log('Book list app started.');
    booksList.init();
};


class BooksList {
    constructor() {
        this.books = [
            {
                title: 'Zabójstwo Rogera Ackroyda',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "T. J. Dehnel",
                year: "2021",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Tajemnicza historia w Styles',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "T. J. Dehnel",
                year: "2021",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Zło czai się wszędzie',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "T. J. Dehnel",
                year: "2021",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Pięć małych świnek',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "I. Kulczycka-Dąmbska",
                year: "2021",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Kurtyna',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "A. Szeryńska",
                year: "2021",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Morderstwo w Mezopotamii',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "J. Zakrzewski",
                year: "2021",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Morderstwo w Orient Expresie',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "M. Kisiel-Małecka",
                year: "2021",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Samotny dom',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "M. Michałowska",
                year: "2021",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'I nie było już nikogo',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "R. Chrząstowski",
                year: "2021",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Śmierć na Nilu',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "N. Billi",
                year: "2021",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Dwanaście prac Herkulesa',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "G. Jesionek",
                year: "2021",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'A.B.C.',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "T. J. Dehnel",
                year: "2019",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Morderstwo na polu Golfowym',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "J. S. Zaus",
                year: "2022",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Zbrodnie zimową porą',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "",
                year: "2021",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Morderstwo na plebanii',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "B. Hrycak",
                year: "2022",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Randez-vous ze śmiercią',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "T. J. Dehnel",
                year: "2022",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Zagadka błękitnego ekspresu',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "H. Pasierska",
                year: "2022",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Wigilia wszystkich świętych',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "K. Masłowski",
                year: "2021",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Noc w bibliotece',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "E. Sicińska-Gałuszkowa",
                year: "2022",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Zerwane zaręczyny',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "T. J. Dehnel",
                year: "2022",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Tajemnica gwiazdkowego puddingu',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "K. Bockenheim",
                year: "2021",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Dom zbrodni',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "A. Rojkowska",
                year: "2022",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Morderstwo w Boże Narodzenie',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "A. Milcarz",
                year: "2022",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Zatrute pióro',
                author: 'Agatha Christie',
                ph: "Wydawnictwo Dolnośląskie",
                translator: "I. Kulczycka",
                year: "2021",
                series: "kolekcjonerska",
                type: "kryminał",
            },
            {
                title: 'Czysty kod - podręcznik dobrego programisty',
                author: 'Robert C. Martin',
                ph: "Helion",
                translator: "P. Gonera",
                year: "2014",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Mistrz czystego kodu - kodeks postępowania profesjonalnych programistów',
                author: 'Robert C. Martin',
                ph: "Helion",
                translator: "W. Moch",
                year: "2013",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Zrozumieć programowanie',
                author: 'Gynvael Coldwind',
                ph: "PWN",
                translator: "",
                year: "2015",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Algorytmy, struktury danych i techniki programowania',
                author: 'Piotr Wróblewski',
                ph: "Helion",
                translator: "",
                year: "2019",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Pragmatyczny programista. Od czeladnika do mistrza.',
                author: 'David Thomas, Andrew Hunt',
                ph: "Helion",
                translator: "",
                year: "2021",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Zrozumieć JavaScript',
                author: 'Marijn Haverbeke',
                ph: "Helion",
                translator: "L. Piwko",
                year: "2019",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Full Stack JavaScript',
                author: 'Azat Mardan',
                ph: "Helion",
                translator: "A. Górczyńska",
                year: "2020",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Święte wijny JavaScriptu',
                author: 'Bartłomiej Borowczyk, Jakób Król',
                ph: "www.ksiazki.it, Programistyczne Świry",
                translator: "",
                year: "2021",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Fotografuj miejsca jak mistrz',
                author: 'Henry Carroll',
                ph: "almapress",
                translator: "J. J. Malinowski",
                year: "2014",
                series: "",
                type: "fotografia",
            },
            {
                title: 'Fotografuj ludzi jak mistrz',
                author: 'Henry Carroll',
                ph: "almapress",
                translator: "J. J. Malinowski",
                year: "2015",
                series: "",
                type: "fotografia",
            },
            {
                title: 'Wracajcie szczęśliwie do bazy',
                author: 'Zbigniew Neugebauer',
                ph: "Książka i Wiedza",
                translator: "",
                year: "1974",
                series: "",
                type: "reportaż, publicystyka, dokument",
            },
            {
                title: 'Zanim wyjedziesz w Bieszczady - Nocny pociąg',
                author: 'Kazimierz Nóżka, Marcin Scelina, Maciej Kozłowski',
                ph: "Znak",
                translator: "",
                year: "2021",
                series: "",
                type: "podróżnicza, reportaż",
            },
            {
                title: 'Zanim wyjedziesz w Bieszczady - Przystanek Jezioro',
                author: 'Kazimierz Nóżka, Marcin Scelina, Maciej Kozłowski',
                ph: "Znak",
                translator: "",
                year: "2020",
                series: "",
                type: "podróżnicza, reportaż",
            },
            {
                title: 'Zanim wyjedziesz w Bieszczady',
                author: 'Kazimierz Nóżka, Marcin Scelina, Maciej Kozłowski',
                ph: "Znak",
                translator: "",
                year: "2019",
                series: "",
                type: "podróżnicza, reportaż",
            },
            {
                title: 'Uczenie maszynowe z językiem JavaScript - rozwiązywanie złożonych problemów',
                author: 'Burak Kanber',
                ph: "Helion",
                translator: "P. Rajca",
                year: "2018",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Programowanie dla początkujących w 24 godziny',
                author: 'Greg Perry, Dean Miller',
                ph: "Helion",
                translator: "T. Walczak",
                year: "2020",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Ci niewiarygodni Inkowie',
                author: 'Terry Deary',
                ph: "Egmont",
                translator: "",
                year: "2018",
                series: "Strrraszna historia",
                type: "historia",
            },
            {
                title: 'Krwawi władcy i wredne królowe',
                author: 'Terry Deary',
                ph: "Egmont",
                translator: "",
                year: "2019",
                series: "Strrraszna historia",
                type: "historia",
            },
            {
                title: 'Ci odjazdowi jaskiniowcy',
                author: 'Terry Deary',
                ph: "Egmont",
                translator: "",
                year: "2019",
                series: "Strrraszna historia",
                type: "historia",
            },
            {
                title: 'To okropne średniowiecze',
                author: 'Terry Deary',
                ph: "Egmont",
                translator: "",
                year: "2018",
                series: "Strrraszna historia",
                type: "historia",
            },
            {
                title: 'Groźni rycerze w ponurych zamczyskach',
                author: 'Terry Deary',
                ph: "Egmont",
                translator: "",
                year: "2019",
                series: "Strrraszna historia",
                type: "historia",
            },
            {
                title: 'Ci okrutni wikingowie',
                author: 'Terry Deary',
                ph: "Egmont",
                translator: "",
                year: "2018",
                series: "Strrraszna historia",
                type: "historia",
            },
            {
                title: 'Niesamowici Egipcjanie',
                author: 'Terry Deary',
                ph: "Egmont",
                translator: "",
                year: "2020",
                series: "Strrraszna historia",
                type: "historia",
            },
            {
                title: 'Tysiąc i Jedna Noc z Szeherezadą',
                author: 'Terry Deary',
                ph: "KOS",
                translator: "M. L. Kalinowski, R. R. Stiller z przekładu niemieckiego, z przekładu arabskiego, z oryginału XV w. Muhsin Mahdi 1983",
                year: "2013",
                series: "",
                type: "ilustrowana, poezja, baśń, mit, literatura piękna",
            },
            {
                title: 'Python w analizie danych - przetwarzanie danych za pomocą pakietów pandas i numpy oraz środowiska ipython',
                author: 'Wes McKinney',
                ph: "Helion, O'Reilly",
                translator: "K. Matuk",
                year: "2018",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'React Native w akcji',
                author: 'Naber Dabit',
                ph: "PWN",
                translator: "",
                year: "2020",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Hello World! Przygoda z programowaniem dla dzieci i alsolutnie początkujących',
                author: 'Warren Sande, Carter Sande',
                ph: "Helion",
                translator: "K. Brauner",
                year: "2017",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Automatyzacja nudnych zadań z pythonem',
                author: 'Albert Sweigart',
                ph: "Helion",
                translator: "R. Górczyński",
                year: "2015",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Java to takie proste - praktyczne wprowadzenie do programowania',
                author: 'Bryson Payne',
                ph: "PWN",
                translator: "W. Sikorski",
                year: "2018",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'ABC programowania w C++',
                author: 'Jan Rusek',
                ph: "Helion",
                translator: "",
                year: "2002",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'C++ Przewodnik dla początkujących',
                author: 'Alex Allain',
                ph: "Helion",
                translator: "I. Jakóbik",
                year: "2012",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Java - podstawy',
                author: 'Cay S. Horstmann',
                ph: "Helion",
                translator: "L. Piwko",
                year: "2019",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Rusz głową - Java',
                author: 'Kathy Sierra, Bert Bates',
                ph: "Helion, O'Reilly",
                translator: "P. Rajca",
                year: "2011",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'HTML, CSS i JavaScript dla każdego',
                author: 'Laura Lemay, Rafe Colburn, Jennifer Kyrnin',
                ph: "Helion",
                translator: "R. Górczyński",
                year: "2016",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'JavaScript i JQuery - interaktywne strony www dla każdego',
                author: 'Jon Duckett',
                ph: "Helion",
                translator: "R. Górczyński",
                year: "2015",
                series: "Podręcznik Front-End Developera",
                type: "programowanie, podręcznik",
            },
            {
                title: 'HTML i CSS - zaprojektuj i zbuduj witrynę www',
                author: 'Jon Duckett',
                ph: "Helion",
                translator: "P. Rajca",
                year: "2014",
                series: "Podręcznik Front-End Developera",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Warsztat hakera - testy penetracyjne i inne techniki wykrywania podatności',
                author: 'Matthew Hickey, Jennifer Arcuri',
                ph: "Helion, Wiley",
                translator: "W. Moch",
                year: "2022",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'JavaScript - przewodnik - poznaj język mistrzów programowania',
                author: 'David Flanagan',
                ph: "Helion, O'Reilly",
                translator: "A. Watrak",
                year: "2021",
                series: "",
                type: "programowanie, podręcznik",
            },
            {
                title: 'Sekrety mistrza fotografii cyfrowej',
                author: 'Scott Kelby',
                ph: "Helion",
                translator: "P. Cieślak",
                year: "2016",
                series: "",
                type: "fotografia",
            },
            {
                title: '500 zagadek fotograficznych',
                author: 'Henryk Latoś',
                ph: "Wiedza powszechna",
                translator: "",
                year: "1981",
                series: "",
                type: "fotografia",
            },
            {
                title: 'Adobe Photoshop Lightroom2 - podręcznik dla fotografów',
                author: 'Martin Evening',
                ph: "Helion",
                translator: "D. Kurek",
                year: "2010",
                series: "",
                type: "fotografia, grafika",
            },
            {
                title: 'Adobe After Effects CC - oficjalny podręcznik',
                author: 'Lisa Fridsma, Brie Gyncild',
                ph: "Helion",
                translator: "Z. Waśko",
                year: "2016",
                series: "",
                type: "fotografia, grafika",
            },
            {
                title: 'Adobe InDesign CC/CC PL - Projektowanie multimediów i publikacji do druku',
                author: 'J. Gordon, C. Jansen, R. Schwartz',
                ph: "Helion",
                translator: "J. Zatorska",
                year: "2017",
                series: "",
                type: "fotografia, grafika",
            },
            {
                title: 'Adobe Photoshop CC/CC PL - oficjalny podręcznik',
                author: 'A. Faulkner, C. Chavez',
                ph: "Helion",
                translator: "Z. Waśko",
                year: "2016",
                series: "",
                type: "fotografia, grafika",
            },
            {
                title: 'Adobe Photoshop PL 2020 - oficjalny podręcznik',
                author: 'A. Faulkner, C. Chavez',
                ph: "Helion",
                translator: "Z. Waśko, P. Cieślak",
                year: "2020",
                series: "",
                type: "fotografia, grafika",
            },
            {
                title: 'Światło w fotografii - magia i nauka',
                author: 'F. Hunter, S. Biver, P. Fuqua',
                ph: "Galaktyka",
                translator: "P. Kazimierczak",
                year: "2007",
                series: "",
                type: "fotografia",
            },
            {
                title: 'Gimp - domowe studio fotograficzne',
                author: 'Lukasz Oberlan',
                ph: "Helion",
                translator: "",
                year: "2003",
                series: "",
                type: "fotografia",
            },
            {
                title: 'Szkoła fotografowania National Geographic',
                author: 'Peter K. Burian, Robert Caputo',
                ph: "National Geographic",
                translator: "M. Hen",
                year: "1999",
                series: "",
                type: "fotografia",
            },
            {
                title: 'Fotografia w praktyce amatorskiej',
                author: 'Zbigniew Pękosławski',
                ph: "Wydawnictwa artystyczne i filmowe",
                translator: "M. Hen",
                year: "1977",
                series: "",
                type: "fotografia",
            },
            {
                title: '1001 fotografii, które musisz zobaczyć',
                author: 'Paul Lowe',
                ph: "Elipsa",
                translator: "K. Krzyżanowski",
                year: "2017",
                series: "",
                type: "fotografia, album",
            },
            {
                title: 'Style w architekturze - arcydzieła budownictwa europejskiego od antyku po czasy współczesne',
                author: 'Wilfried Koch',
                ph: "Świat Książki, Mosaik Verlag",
                translator: "",
                year: "1996",
                series: "",
                type: "sztuka, architektura, podręcznik",
            },
            {
                title: 'Wizja fotografa - jak czytać i rozumieć wspaniałe zdjęcia',
                author: 'M. Freeman',
                ph: "National Geographic",
                translator: "M. Jabłoński",
                year: "2011",
                series: "",
                type: "fotografia",
            },
            {
                title: 'Pracując ze światłem - warsztaty fotografii krajobrazowej',
                author: 'J. Cornish, Ch. Waite, D. Ward, E. Ephraums',
                ph: "Galaktyka",
                translator: "W. Tkaczyński",
                year: "2009",
                series: "",
                type: "fotografia",
            },
            {
                title: 'Sztuka czarno-białej fotografii - od inspiracji do obrazu',
                author: 'T. A. Hoffmann',
                ph: "Helion",
                translator: "T. Boszko",
                year: "2009",
                series: "",
                type: "fotografia",
            },
            {
                title: 'Photosjop w cyfrowej ciemni - kreatywna obróbka obrazu',
                author: 'H. Davis, P, Davis',
                ph: "Helion",
                translator: "P. Cieślak",
                year: "2011",
                series: "",
                type: "fotografia, grafika",
            },

        ];
    };

    booksList = document.getElementById("myUL");


    init() {
        this.displayBooksList();
        this.myFunction();
    };

    myFunction() {
        let input, filter, ul, li, a, i, txtValue;
        input = document.getElementById('myInput');
        filter = input.value.toUpperCase();
        ul = document.getElementById("myUL");
        li = ul.getElementsByTagName('li');

        for (i = 0; i < li.length; i++) {
            a = li[i].getElementsByTagName("a")[0];
            txtValue = a.textContent || a.innerText || a.innerHTML;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                li[i].style.display = "";
            } else {
                li[i].style.display = "none";
            }
        }
    }

    displayBooksList() {
        for (let i = 0; i < this.books.length; i++) {
            let book = this.books[i];
            const liItem = document.createElement("li");
            this.booksList.appendChild(liItem);
            liItem.innerHTML = `
                <li><a href="#"> ${book.title} - ${book.author} ${book.translator ? " - przekład " + book.translator : ""} ${book.ph ? " - " + book.ph : ""} ${book.year ? " - " + book.year : ""} ${book.series ? " - " + book.series.italics() : ""} ${book.type ? " (" + book.type +") " : ""} </a></li>
            `;
        }
    }
};

const booksList = new BooksList();



